on:
  push:
  workflow_dispatch:
  watch:
    types: [started]

env:
  GROUP_ID: com.octokat.app
  ARTIFACT_ID: maven-publish-classifier
  CLASS_NAME: PublishApp

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        classifier: ["simple", "with-dash", "with.dot", "with_underscore", "camelCase"]

    env:
      CLASSIFIER: ${{ matrix.classifier }}
      VERSION: 1.0.${{ strategy.job-index }}-SNAPSHOT

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add simple pom.xml
        run: |
          cat > pom.xml << EOM
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>${{ env.GROUP_ID }}</groupId>
            <artifactId>${{ env.ARTIFACT_ID }}</artifactId>
            <version>${{ env.VERSION }}</version>
            <build>
              <pluginManagement>
                <plugins>
                  <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.0.2</version>
                    <configuration>
                      <classifier>${{ env.CLASSIFIER }}</classifier>
                    </configuration>
                  </plugin>
                </plugins>
              </pluginManagement>
            </build>
          </project>
          EOM

      - name: Add ${{ env.CLASS_NAME }}.java file
        run: |
          SOURCE_DIR=src/main/java/$(echo ${{ env.GROUP_ID }} | tr . /)
          mkdir -p $SOURCE_DIR
          SOURCE_PATH=$SOURCE_DIR/${{ env.CLASS_NAME }}.java
          cat <<- END > $SOURCE_PATH
          package ${{ env.GROUP_ID }};
          public class ${{ env.CLASS_NAME }}
          {
              public static void main( String[] args )
              {
                  System.out.println( "Hello from ${{ github.repository }}, commit ${{ github.sha }}, run number ${{ github.run_number }}!" );
              }
          }
          END

      - name: Build package
        run: mvn package --no-transfer-progress

      - name: Run package
        run: java -cp target/${{ env.ARTIFACT_ID }}-${{ env.VERSION }}-${{ env.CLASSIFIER }}.jar ${{ env.GROUP_ID }}.${{ env.CLASS_NAME }}

      - name: Deploy package
        run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password

  install:
    needs: [deploy]

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        classifier: ["simple", "with-dash", "with.dot", "with_underscore", "camelCase"]

    env:
      CLASSIFIER: ${{ matrix.classifier }}
      VERSION: 1.0.${{ strategy.job-index }}-SNAPSHOT

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add pom.xml with dependency
        run: |
          cat > pom.xml << EOM
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>${{ env.GROUP_ID }}</groupId>
            <artifactId>${{ env.ARTIFACT_ID }}-install</artifactId>
            <version>${{ env.VERSION }}</version>
            <dependencies>
              <dependency>
                <groupId>${{ env.GROUP_ID }}</groupId>
                <artifactId>${{ env.ARTIFACT_ID }}</artifactId>
                <version>${{ env.VERSION }}</version>
                <classifier>${{ env.CLASSIFIER }}</classifier>
              </dependency>    
            </dependencies>
            <repositories>
              <repository>
                <id>github</id>
                <url>https://maven.pkg.github.com/${{ github.repository_owner }}/*</url>
              </repository>
            </repositories>
          </project>
          EOM

      - name: Install packages
        run: mvn install --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ github.token }}

  dump:
    needs: [deploy]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        classifier: ["simple", "with-dash", "with.dot", "with_underscore", "camelCase"]

    env:
      CLASSIFIER: ${{ matrix.classifier }}
      VERSION: 1.0.${{ strategy.job-index }}-SNAPSHOT

    steps:
      - name: Dump maven-metadata.xml
        run: |
          sudo apt-get install libxml2-utils
          curl https://maven.pkg.github.com/jcansdale-test/maven-publish-classifier/${{ env.GROUP_ID }}/${{ env.ARTIFACT_ID }}/${{ env.VERSION }}/maven-metadata.xml -v -u token:${{ github.token }} | xmllint --format -
